### ISSUE TITLE
change to read data from github

### ISSUE THREAD

**Issue by opetchey** [opetchey/ecopredtools#2]

**Comment by opetchey** [comment]
Frank, I can do this for csv files, but can't get it working for Rdata files. I looked [here](http://stackoverflow.com/questions/24846120/importing-data-into-r-rdata-from-github) but none of the ideas seem to work. Can you solve this?

**Comment by pennekampster** [comment]
Yes, I will look into it!

**Comment by opetchey** [comment]
Thanks Frank!

**Comment by pennekampster** [comment]
Ok, I think it works thanks to the source_data function from repmis package.

**Comment by opetchey** [comment]
Super, thanks Frank.
